# Site settings
title: Your Lab Notebook # type your own lablog title here

description: > # this means to ignore newlines until "baseurl:"
  write a description of your notebook
baseurl: "/your_compsysmed_labnotebook" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
include: [ _assets , _projects ]

name : FirstName LastName
email : email@email.com
github_username: Github username

# Build settings
markdown: kramdown
kramdown:
  input: GFM

noindex: true # if true, google will ignore your pages!

defaults:   # overwrite with in YAML frontmatter, e.g. 'place: New York'
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      place:  # default Geolocation of posts.
      author: 'your name' # default author for posts (for multi-authoring)
